# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#cache: packages
sudo: false
bioc_required: true
bioc_use_devel: true
warnings_are_errors: false
notifications:
    email: false
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
